SCREEN_WIDTH, SCREEN_HEIGHT = 800, 600
CELL_SIZE = 8
GRID_WIDTH = SCREEN_WIDTH // CELL_SIZE
GRID_HEIGHT = SCREEN_HEIGHT // CELL_SIZE

grid = [[None for _ in range(GRID_HEIGHT)] for _ in range(GRID_WIDTH)]